"""
Django settings for trackx project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production set DJANGO_SECRET_KEY env var. Refuse to boot publicly with
# the baked-in dev key when DEBUG is off.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-^_%nadu!!9cec(qkpgb5x%$)fgerp5z5)fk)j^r!xy#+gew*i#',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to ON for local dev convenience; production compose files set
# DJANGO_DEBUG=0 explicitly (and VERCEL=1 legacy flag forces it off).
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1' and os.environ.get('VERCEL') != '1'

if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise RuntimeError(
        'Refusing to start with the insecure dev SECRET_KEY while DEBUG is off. '
        'Set a strong DJANGO_SECRET_KEY environment variable.'
    )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', '*').split(',')
    if h.strip()
]

_PUBLIC_HOST = os.environ.get('PUBLIC_HOST', '').strip()

CSRF_TRUSTED_ORIGINS = [
    'https://*.vusercontent.net',
    'https://*.v0.dev',
    'https://*.vercel.app',
    'http://localhost:3000',
] + ([f'https://{_PUBLIC_HOST}'] if _PUBLIC_HOST else [])

# CORS: allow the local React (Vite) dev server to consume the REST + WS APIs.
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:3000',
] + ([f'https://{_PUBLIC_HOST}'] if _PUBLIC_HOST else [])

# Behind Caddy/Nginx TLS terminator: honor X-Forwarded-Proto so Django builds
# https:// URLs and CSRF checks pass. Cookies only gain Secure flag when we
# actually serve HTTPS (PUBLIC_HOST set) to avoid breaking local http.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if _PUBLIC_HOST:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'rest_framework',
    'corsheaders',
    'dashboard',
    'anpr_engine',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trackx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trackx.wsgi.application'
ASGI_APPLICATION = 'trackx.asgi.application'

_REDIS_URL = os.environ.get('REDIS_URL')
CHANNEL_LAYERS = {
    'default': {
        # Use Redis in production (Docker), fall back to in-memory for local dev
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # Pass socket_timeout=None: redis-py 8.x defaults to a 5s socket
            # read timeout, which races Channels' idle BRPOP/BZPOPMIN polling.
            # When no message arrives, the read times out first, raising
            # "Timeout reading from redis" and killing every idle WebSocket
            # consumer after ~5s.
            'hosts': [{'address': _REDIS_URL, 'socket_timeout': None}],
            'capacity': 1500,
            'expiry': 10,
        },
    },
} if _REDIS_URL else {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('POSTGRES_DB', 'trackx_db'),
        'USER': os.environ.get('POSTGRES_USER', 'postgres'),
        'PASSWORD': os.environ.get('POSTGRES_PASSWORD', 'satyam3s'),
        'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
        'PORT': os.environ.get('POSTGRES_PORT', '5432'),
    }
}

# GeoDjango: resolve GDAL/GEOS shared libraries on this Windows dev machine.
# Only applied when the pip-installed osgeo package (with its DLLs) actually
# exists; on Linux containers/system installs, Django auto-detects GDAL/GEOS.
# Environment variables take precedence when explicitly provided.
_OSGEO_DIR = os.path.join(
    os.environ.get('APPDATA', ''),
    'Python', 'Python314', 'site-packages', 'osgeo',
)
if os.environ.get('GDAL_LIBRARY_PATH'):
    GDAL_LIBRARY_PATH = os.environ['GDAL_LIBRARY_PATH']
elif os.path.isfile(os.path.join(_OSGEO_DIR, 'gdal.dll')):
    GDAL_LIBRARY_PATH = os.path.join(_OSGEO_DIR, 'gdal.dll')

if os.environ.get('GEOS_LIBRARY_PATH'):
    GEOS_LIBRARY_PATH = os.environ['GEOS_LIBRARY_PATH']
elif os.path.isfile(os.path.join(_OSGEO_DIR, 'geos_c.dll')):
    GEOS_LIBRARY_PATH = os.path.join(_OSGEO_DIR, 'geos_c.dll')


# Celery async task configuration (Redis broker + result backend)
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
# Collectstatic target: /app/staticfiles in Docker, BASE_DIR/staticfiles
# locally. Overridable via STATIC_ROOT env (legacy Vercel used /tmp).
STATIC_ROOT = os.environ.get('STATIC_ROOT', str(BASE_DIR / 'staticfiles'))

# Uploaded media (video feeds + plate crops). Shared across web/celery via
# the `trackx_media` volume so async workers can read uploads.
MEDIA_ROOT = os.environ.get('MEDIA_ROOT', '/app/media')
MEDIA_URL = '/media/'

# Serve static assets directly with WhiteNoise. Finder mode lets it read from
# STATICFILES_DIRS at runtime, so no collectstatic build step is required.
WHITENOISE_USE_FINDERS = True
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Console logging so ANPR/Channels errors surface in Daphne/Celery logs
# (Django's default config only wires up a few framework loggers).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {'format': '[%(levelname)s] %(name)s: %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        'anpr_engine': {'level': 'INFO', 'handlers': ['console'], 'propagate': False},
    },
}
